### ISSUE TITLE
Shaking of the model

### ISSUE THREAD

**Issue by tcmmx** [Hypnosss/cesium-babylonjs#1]
Good work . Can you fix the shaking of the model ? when you zoom in

**Comment by wkhyh** [comment]
Yes, i think it maybe cause by precision of position and rotation

**Comment by wkhyh** [comment]
set engine prop **useHighPrecisionMatrix : true**

**Comment by luozr** [comment]
测试了下，下面这样是不会抖动了
  const engine = new BABYLON.Engine(canvas, false, {
    useHighPrecisionMatrix: true,
  });
