### ISSUE TITLE
The babylon model flips.

### ISSUE THREAD

**Issue by zicai1** [Hypnosss/cesium-babylonjs#5]
When I load the babylon model into cesium using this code of yours, the model is mirror flipped, what is the reason for this?
<img width="755" alt="babylon" src="https://github.com/user-attachments/assets/a4270e3d-d534-4f21-b516-f89833f10619">
<img width="806" alt="cesium" src="https://github.com/user-attachments/assets/35af8d07-2c08-4c17-9325-45233382395b">

**Comment by mchao123** [comment]
加个变形翻转回来[狗头]
